### ISSUE TITLE
TP6不能用，require-dev中依赖yunwuxin/think-mail，但yunwuxin/think-mail还不支持TP6

### ISSUE THREAD

**Issue by liuwave** [yunwuxin/think-notification#3]
TP6不能用，require-dev中依赖yunwuxin/think-mail，但yunwuxin/think-mail还不支持TP6.....

这不是官方推荐的插件吗？

**Comment by yunwuxin** [comment]
你正常安装  怎么会安装到dev依赖

yunwuxin/think-mail 只是一个可选组件

**Comment by liuwave** [comment]
@yunwuxin 嗯，看错，是notification 2.0.1的报错。
用的 ` composer require yunwuxin/think-notification`  ， 装的是2.0.1。
 应该装3.0.x-dev。
